#!/usr/bin/env node
/*
 * Content build: packs Markdown sources from /content into one JS bundle per language
 * (assets/data/content.<lang>.js). Bundles are plain scripts, so the site works both on
 * GitHub Pages and when index.html is opened directly from disk (file://).
 *
 * Usage:  node tools/build.js
 *
 * Markdown file layout (content/<lang>/<nn>-<slug>.md):
 *   ---                      front matter (key: value)
 *   id: t03
 *   type: topic | page
 *   ...
 *   ---
 *   lecture body (Markdown)
 *   === summary ===          optional: short notes ("konspekt")
 *   === tasks ===            optional: exercises
 *
 * Inside code fences a line "@include file.java" is replaced with content/code/file.java.
 */
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const contentDir = path.join(root, 'content');
const codeDir = path.join(contentDir, 'code');
const outDir = path.join(root, 'assets', 'data');
const LANGS = ['pl', 'en', 'ru'];

function parseFrontMatter(src, file) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/.exec(src);
  if (!m) throw new Error('Missing front matter in ' + file);
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const i = line.indexOf(':');
    if (i > 0) meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { meta, body: src.slice(m[0].length) };
}

function includeCode(text, file) {
  return text.replace(/^([ \t]*)@include[ \t]+(\S+)[ \t]*$/gm, (_, indent, name) => {
    const p = path.join(codeDir, name);
    if (!fs.existsSync(p)) throw new Error(`@include ${name} not found (in ${file})`);
    return fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n').replace(/\n+$/, '')
      .split('\n').map(l => (l ? indent + l : l)).join('\n');
  });
}

function splitParts(body) {
  const parts = { body, summary: '', tasks: '' };
  const re = /^===[ \t]*(summary|tasks)[ \t]*===[ \t]*$/gm;
  const marks = [];
  let m;
  while ((m = re.exec(body))) marks.push({ name: m[1], start: m.index, end: m.index + m[0].length });
  if (!marks.length) return parts;
  parts.body = body.slice(0, marks[0].start);
  marks.forEach((mk, i) => {
    parts[mk.name] = body.slice(mk.end, i + 1 < marks.length ? marks[i + 1].start : body.length);
  });
  return parts;
}

function buildLang(lang) {
  const dir = path.join(contentDir, lang);
  const files = fs.readdirSync(dir).filter(f => f.endsWith('.md')).sort();
  const topics = [];
  const pages = {};
  for (const f of files) {
    const src = fs.readFileSync(path.join(dir, f), 'utf8').replace(/\r\n/g, '\n');
    const { meta, body } = parseFrontMatter(src, f);
    const parts = splitParts(includeCode(body, f));
    const entry = Object.assign({}, meta, {
      body: parts.body.trim(),
      summary: parts.summary.trim(),
      tasks: parts.tasks.trim()
    });
    if (meta.type === 'page') pages[meta.id] = entry;
    else topics.push(entry);
  }
  topics.sort((a, b) => Number(a.num) - Number(b.num));
  const json = JSON.stringify({ topics, pages });
  const out = `/* Generated by tools/build.js - do not edit by hand. */\nwindow.ASD.content.register(${JSON.stringify(lang)}, ${json});\n`;
  fs.writeFileSync(path.join(outDir, `content.${lang}.js`), out);
  return { topics: topics.length, pages: Object.keys(pages).length, kb: Math.round(out.length / 1024) };
}

fs.mkdirSync(outDir, { recursive: true });
for (const lang of LANGS) {
  const r = buildLang(lang);
  console.log(`${lang}: ${r.topics} topics, ${r.pages} pages, ${r.kb} KB`);
}
